### ISSUE TITLE
Back-release for smver

### ISSUE THREAD

**Issue by bsiranosian** [conda-forge/semver-feedstock#7]
Hi, I'm writing a recipe for `pkutils` on conda-forge which requires `smver >=2.2.1,<2.7.3`, see https://github.com/reubano/pkutils/blob/master/requirements.txt

Is it possible to get a back release, as the minimum version of smver is 2.7.5.

See the recipe PR here: https://github.com/conda-forge/staged-recipes/pull/7236

Thanks!

**Comment by carlodri** [comment]
Done in #9
